---
name: tests

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: hello_world
      run: echo "hello world"
    - name: list_content
      run: ls -l
    - name: current_directory
      run: pwd

    - name: Clone repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Moxunit and MOcov
      run: |
        git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
        git clone https://github.com/MOcov/MOcov.git --depth 1

    # - name: Install MATLAB
    #   uses: matlab-actions/setup-matlab@v1.2.4
    #   with:
    #     release: R2020a

    # - name: Run unit tests MATLAB
    #   uses: matlab-actions/run-command@v1.1.2
    #   with:
    #     command: |
    #       cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run Tests_Matlab_GH;

    # - name: Check unit tests
    #   run: cat doc/testing/test_report.log | grep 0
